// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCMwCjD7sDIzSuU0WfkRjNM1EUtXX2mUYM",
      authDomain: "markme-88aa8.firebaseapp.com",
      projectId: "markme-88aa8",
      storageBucket: "markme-88aa8.firebasestorage.app",
      messagingSenderId: "1095035286846",
      appId: "1:1095035286846:web:13a58430433bf57183286f",
      measurementId: "G-G6M5Q3CC75"
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTdwkEeVjIUANb7vngTy2Mxckf-mYHuKs',
    appId: '1:1095035286846:android:ffdf235403650b5483286f',
    messagingSenderId: '1095035286846',
    projectId: 'markme-88aa8',
    storageBucket: 'markme-88aa8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPWQq0shMiog12fzmEWma6NQhCkgBrKKw',
    appId: '1:1095035286846:ios:2e018ad84e910c6583286f',
    messagingSenderId: '1095035286846',
    projectId: 'markme-88aa8',
    storageBucket: 'markme-88aa8.firebasestorage.app',
    iosBundleId: 'com.example.markmeStudent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPWQq0shMiog12fzmEWma6NQhCkgBrKKw',
    appId: '1:1095035286846:ios:ae7588666edb5b8f83286f',
    messagingSenderId: '1095035286846',
    projectId: 'markme-88aa8',
    storageBucket: 'markme-88aa8.firebasestorage.app',
    iosBundleId: 'com.oxiionglobal.markme.student',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMwCjD7sDIzSuU0WfkRjNM1EUtXX2mUYM',
    appId: '1:1095035286846:web:4994f39c60f89b8a83286f',
    messagingSenderId: '1095035286846',
    projectId: 'markme-88aa8',
    authDomain: 'markme-88aa8.firebaseapp.com',
    storageBucket: 'markme-88aa8.firebasestorage.app',
    measurementId: 'G-J5T59S8BSG',
  );
}